events { worker_connections 1024; }
http {
  upstream app { server app1:8000; server app2:8000; }
  server {
    listen 80;
    location / {
      proxy_pass http://app;
      proxy_set_header X-Api-Key $http_x_api_key;
    }
  }
}
